version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-dev
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Admin@123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass Redis@123
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data:
